hapi:
  fhir:
    # server_address: http://localhost:8080/fhir
    server_address: https://hapi-fhir.wecare.localhost/fhir
    default_encoding: json
    # dao_config.server_id_mode: UUID
    custom_content_path: /custom
